# Generated by Django 5.1.4 on 2024-12-31 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_transaction_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('transaction_method', models.CharField(choices=[('ATM', 'ATM 거래'), ('TRANSFER', '계좌이체'), ('AUTOMATIC_TRANSFER', '자동이체'), ('CARD', '카드결제'), ('INTEREST', '이자')], max_length=30)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', '입금'), ('WITHDRAW', '출금')], max_length=30)),
                ('transaction_timestamp', models.DateTimeField(db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
