# Generated by Django 5.1.4 on 2025-01-02 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='post_transaction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
    ]
